FROM laudio/pyodbc:1.0.38

ENV TZ="Europe/Istanbul"
ENV LC_ADDRESS=C.UTF-8
ENV LC_NAME=C.UTF-8
ENV LC_MONETARY=C.UTF-8
ENV LOGNAME=root
ENV LC_PAPER=C.UTF-8
ENV LC_IDENTIFICATION=C.UTF-8
ENV LC_TELEPHONE=C.UTF-8
ENV LC_MEASUREMENT=C.UTF-8
ENV LC_TIME=C.UTF-8
ENV LC_NUMERIC=C.UTF-8

WORKDIR sorgulayici
COPY src/ .
RUN yes | pip install -r requirements.txt

CMD ["python3", "./main.py"]
